### ISSUE TITLE
Logs (DEBUG level) go overwhelming when there are some pending requests

### ISSUE THREAD

**Issue by yangwwei** [apache/incubator-yunikorn-k8shim#37]
Lots of logs were from predicator and some from the core scheduling process. We need to fix this. I can see it goes to hundreds of MBs after running for a while when there are some pending requests.

**Comment by TaoYang526** [comment]
@yangwwei  perhaps it's related to #54 , scheduling-task logs can be printed repeatedly.

**Comment by wilfred-s** [comment]
moved to jira:
https://issues.apache.org/jira/browse/YUNIKORN-25
